apiVersion: apps/v1
kind: Deployment
metadata:
  name: trt-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-deployment-app
  template:
    metadata:
      labels:
        app: simple-deployment-app
    spec:
      containers:
        - name: trt-app-instance
          image: trthhrts/simple_app:v3
          ports:
            - name: web
              containerPort: 8000