fullnameOverride: postgres
postgresqlUsername: trtuser
postgresqlPassword: passwd
postgresqlDatabase: trtdb

service:
  type: NodePort
  port: 5432

persistence:
  enabled: true
  size: 1Gi

resources:
  requests:
    memory: 256Mi
    cpu: 250m